### PR TITLE
merge yieldbot branch back into develop

### PR DESCRIPTION
**Pull request by sorenmacbeth**
A lot of stuff has happened here. This is version that we've been running in production for a good while now. 

Highlights are:

-fixed the threading issues which caused kryo to fails
-removed the re-namespaced storm7 version of thrift in favor of the apache thrift 0.8.0 release
-added leveldb persistence
-various production operational hardening and fixes

I'd like to get this merged back in asap. I'd like @nathanmarz or @sritchie to confirm that switching to thrift 0.8.0 is ok. Once I have that I'll go ahead and merge the pull request. 

I'd like to get us synced back up before I start working on issue #10 (breaking up the monolithic jar into sub projects).

### CODE REVIEW

**Comment by sorenmacbeth** [comment]
If I don't hear any objections by Tuesday, I'll go ahead and merge this.

**Comment by sritchie** [comment]
Do it!  

## 

Sam Ritchie
703.662.1337
@sritchie

**Comment by sorenmacbeth** [comment]
Up to you, but you might want to add my account `sorenmacbeth` to the
elephantdb group on clojars so I can push up builds as well.

On Fri, Jan 18, 2013 at 8:24 PM, Sam Ritchie notifications@github.comwrote:

> Do it!
> 
> ## 
> 
> Sam Ritchie
> 703.662.1337
> @sritchie
> 
> On Friday, January 18, 2013 at 7:56 PM, Soren Macbeth wrote:
> 
> > If I don't hear any objections by Tuesday, I'll go ahead and merge this.
> > 
> > —
> > Reply to this email directly or view it on GitHub (
> > https://github.com/nathanmarz/elephantdb/pull/11#issuecomment-12450056).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nathanmarz/elephantdb/pull/11#issuecomment-12450290.

## 

http://about.me/soren

**Comment by sritchie** [comment]
Nathan, I think you own that group?  

## 

Sam Ritchie
703.662.1337
@sritchie

**Comment by sorenmacbeth** [comment]
Ping. Once I can push artifacts up to clojars I can bring the rest of the develop branches of the edb toolchain up to date. Just need to be added to the elephantdb group on clojars.

**Comment by nathanmarz** [comment]
Done

**Pull request merged**
